import React from 'react';
import ReactDOM from 'react-dom';
import './assets/css/style.css';
import App from './App';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Provider } from 'react-redux';
import store from './reducer/index';
import registerServiceWorker from './registerServiceWorker';
ReactDOM.render( <Provider store={store}><App/></Provider>, document.getElementById('root'));
registerServiceWorker();
